name: test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-18.04
          - macos-latest
        compiler:
          - gcc
          - clang

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: bin/test
