name: test

on:
  push:
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - g++
          - clang++

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: bin/test
